using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ShenYangRemoteSystem.Subclass
{
    public class D2PLC1Variables
    {
        // D2PLC1
        public ushort LargeCarElectricCurrent_2 { get; set; } // 1
        public ushort RotaryElectricCurrent_2 { get; set; }
        public ushort SuspensionBeltElectricCurrent_2 { get; set; }
        public ushort BucketWheelElectricCurrent_2 { get; set; }
        public ushort LargeCarTravelDistance_2 { get; set; } //大车行走距离
        public ushort RotaryAngle_2 { get; set; } //回转角度
        public ushort VariableAmplitudeAngle_2 { get; set; } //变幅角度
        public bool VacuumCircuitBreakerClosed_2 { get; set; }
        public bool LowVoltageControlPowerClosed_2 { get; set; }
        public bool LowVoltagePowerClosed_2 { get; set; }
        public bool LargeCarCentralizedLubricationLowOilLevel_2 { get; set; }
        public bool LargeCarCentralizedLubricationOilBlockage_2 { get; set; }
        public bool AllowBucketWheelMaterialLoading_2 { get; set; }
        public bool AllowBucketWheelMaterialUnloading_2 { get; set; }
        public bool LargeCarMainCircuitBreaker_2 { get; set; }
        public bool LargeCarMotorCircuitBreaker_2 { get; set; }
        public bool LargeCarBrakeCircuitBreaker_2 { get; set; }
        public bool LargeCarFrequencyConverterContact_2 { get; set; }
        public bool LargeCarBrakeContact_2 { get; set; }
        public bool LargeCarFrequencyConverterFault_2 { get; set; }
        public bool LargeCarBrakeResistorOverheatSwitch_2 { get; set; }
        public bool LargeCarForwardLimit_2 { get; set; }
        public bool LargeCarReverseLimit_2 { get; set; }
        public bool LargeCarForwardExtremeLimit_2 { get; set; }
        public bool LargeCarReverseExtremeLimit_2 { get; set; }
        public bool CableReelMainCircuitBreaker_2 { get; set; }
        public bool CableReelMotorOverload_2 { get; set; }
        public bool PowerReelContact_2 { get; set; }
        public bool ReelOverTensionLimit1_2 { get; set; }
        public bool ReelOverLooseLimit1_2 { get; set; }
        public bool VibrationMotorMainCircuitBreaker_2 { get; set; }
        public bool RotaryBrakeOverload_2 { get; set; }
        public bool RotaryMainCircuitBreaker_2 { get; set; }
        public bool ClampMotorOverload_2 { get; set; }
        public bool LeftAnchorLiftLimit_2 { get; set; }
        public bool RightAnchorLiftLimit_2 { get; set; }
        public bool LeftClampRelaxLimit_2 { get; set; }
        public bool RightClampRelaxLimit_2 { get; set; }
        public bool BucketWheelMotorMainCircuitBreaker_2 { get; set; }
        public bool RotaryFanContact_2 { get; set; }
        public bool RotaryBrakeContact_2 { get; set; }
        public bool RotaryFrequencyConverterContact_2 { get; set; }
        public bool SystemInterlockSwitch_2 { get; set; }
        public bool VariableAmplitudeMainCircuitBreaker_2 { get; set; }
        public bool VariableAmplitudeMotorOverload_2 { get; set; }
        public bool VariableAmplitudeMotorContact_2 { get; set; }
        public bool VariableAmplitudeHeaterContact_2 { get; set; }
        public bool VariableAmplitudeFanContact_2 { get; set; }
        public bool SuspensionBeltMainCircuitBreaker_2 { get; set; }
        public bool SuspensionBeltMotorOverload_2 { get; set; }
        public bool SuspensionBeltMaterialLoadingRunningContact_2 { get; set; }
        public bool SuspensionBeltMaterialUnloadingRunningContact_2 { get; set; }
        public bool SuspensionBeltBrakeContact_2 { get; set; }
        public bool CentralMaterialDustDetectionSwitch_2 { get; set; }
        public bool DiversionBaffleMainCircuitBreaker_2 { get; set; }
        public bool VibrationMotorOverload_2 { get; set; }
        public bool ClampMainCircuitBreaker_2 { get; set; }
        public bool BucketWheelMotorOverload_2 { get; set; }
        public bool BucketWheelLubricationPumpContact_2 { get; set; }
        public bool RotaryLeftTurnLimit_2 { get; set; }
        public bool RotaryRightTurnLimit_2 { get; set; }
        public bool RotaryLeftTurnExtremeLimit_2 { get; set; }
        public bool RotaryRightTurnExtremeLimit_2 { get; set; }
        public bool RotaryLeftTurnForbiddenZoneLimit_2 { get; set; }
        public bool RotaryRightTurnForbiddenZoneLimit_2 { get; set; }
        public bool RotaryZeroPositionLimit_2 { get; set; }
        public bool BucketWheelOverTorqueSwitch_2 { get; set; }
        public bool BucketWheelForcedLubricationFlowSwitch_2 { get; set; }
        public bool VariableAmplitudeUpperLimit_2 { get; set; }
        public bool VariableAmplitudeLowerLimit_2 { get; set; }
        public bool VariableAmplitudeUpperExtremeLimit_2 { get; set; }
        public bool VariableAmplitudeLowerExtremeLimit_2 { get; set; }
        public bool VariableAmplitudeLowerForbiddenZoneLimit_2 { get; set; }
        public bool CabinFrontBalanceLimit_2 { get; set; }
        public bool VariableAmplitudeOilHeaterStartup_2 { get; set; }
        public bool VariableAmplitudeOilHeaterStop_2 { get; set; }
        public bool VariableAmplitudeFanStop_2 { get; set; }
        public bool VariableAmplitudeFanStartup_2 { get; set; }
        public bool VariableAmplitudeOilLevelLowSignal_2 { get; set; }
        public bool VariableAmplitudePumpStationOverheatAlarm_2 { get; set; }
        public bool VariableAmplitudeOilLevelVeryLowSignal_2 { get; set; }
        public bool RotaryCentralizedLubricationLowOilLevelFault_2 { get; set; }
        public bool LargeCarFrequencyConverterPowerOn_2 { get; set; }
        public bool LargeCarBrakeOpen_2 { get; set; }
        public bool LargeCarFrequencyConverterFaultReset_2 { get; set; }
        public bool LargeCarReverseCommand_2 { get; set; }
        public bool LargeCarHighLowSpeedSelection_2 { get; set; }
        public bool BucketWheelMaterialLoadingRunning_2 { get; set; }
        public bool BucketWheelFault_2 { get; set; }
        public bool SuspensionBeltFirstLevelDeviationSwitch_2 { get; set; }
        public bool SuspensionBeltSecondLevelDeviationSwitch_2 { get; set; }
        public bool SuspensionBeltEmergencyStopSwitch_2 { get; set; }
        public bool SuspensionBeltSpeedDetectionSwitch_2 { get; set; }
        public bool SuspensionBeltMaterialFlowDetectionSwitch_2 { get; set; }
        public bool SuspensionBeltLongitudinalTearSwitch_2 { get; set; }
        public bool RotaryCentralizedLubricationOilBlockageFault_2 { get; set; }
        public bool LargeCarForwardCommand_2 { get; set; }
        public bool VariableAmplitudeOilPumpMotorRunning_2 { get; set; }
        public bool VariableAmplitudeOilHeaterRunning_2 { get; set; }
        public bool VariableAmplitudeFanRunning_2 { get; set; }
        public bool LeftClampPumpRunning_2 { get; set; }
        public bool RightClampPumpRunning_2 { get; set; }
        public bool LeftClampElectromagneticValveOpen_2 { get; set; }
        public bool RightClampElectromagneticValveOpen_2 { get; set; }
        public bool RotaryFrequencyConverterPowerOn_2 { get; set; }
        public bool RotaryBrakeOpen_2 { get; set; }
        public bool RotaryLeftTurnCommand_2 { get; set; }
        public bool RotaryRightTurnCommand_2 { get; set; }
        public bool RotaryFrequencyConverterFaultReset_2 { get; set; }
        public bool RotarySpeedGivenSelection_2 { get; set; }
        public bool RotaryFanRunning_2 { get; set; }
        public bool VariableAmplitudeLowerElectromagneticValveOpen_2 { get; set; }
        public ushort RiseCount_2 { get; set; }
        public bool SingleAction_2 { get; set; }
        public bool LinkAction_2 { get; set; }
        public bool Automatic_2 { get; set; }
        public bool LargeCarFault_2 { get; set; }
        public bool LargeCarForwardLimiting_2 { get; set; }
        public bool LargeCarReverseLimiting_2 { get; set; }
        public bool AnchorClamp_2 { get; set; }
        public bool LargeCarForward_2 { get; set; }
        public bool LargeCarReverse_2 { get; set; }
        public bool RotaryFault_2 { get; set; }
        public bool RotaryLeftTurnLimiting_2 { get; set; }
        public bool RotaryRightTurnLimiting_2 { get; set; }
        public bool RotaryLeftTurn_2 { get; set; }
        public bool RotaryRightTurn_2 { get; set; }
        public bool VariableAmplitudeFault_2 { get; set; }
        public bool VariableAmplitudeUpperLimiting_2 { get; set; }
        public bool VariableAmplitudeLowerLimiting_2 { get; set; }
        public bool VariableAmplitudeUpper_2 { get; set; }
        public bool VariableAmplitudeLower_2 { get; set; }
        public bool SuspensionBeltFault_2 { get; set; }
        public bool SuspensionBeltManualLoading_2 { get; set; }
        public bool SuspensionBeltManualUnloading_2 { get; set; }
        public bool SuspensionBeltLinkLoading_2 { get; set; }
        public bool SuspensionBeltLinkUnloading_2 { get; set; }
        public bool BucketWheelFaulting_2 { get; set; }
        public bool BucketWheelSingleStartup_2 { get; set; }
        public bool BucketWheelLinkStartup_2 { get; set; }
        public bool ClampFault_2 { get; set; }
        public bool ClampRelax_2 { get; set; }
        public bool CentralBaffleFault_2 { get; set; }
        public bool TailCarBeltFault_2 { get; set; }
        public bool MaterialLevelMeter_2 { get; set; }
        public bool ManualIntervention_2 { get; set; }
        public bool InterventionRelease_2 { get; set; }
        public bool SuspensionBeltLoadingButton_2 { get; set; }
        public bool SuspensionBeltStopButton_2 { get; set; }
        public bool SuspensionBeltUnloadingButton_2 { get; set; }
        public bool BucketWheelStartupButton_2 { get; set; }
        public bool BucketWheelStopButton_2 { get; set; }
        public ushort RotaryCount_2 { get; set; }
        public bool LeftAnchorNotLifted_2 { get; set; }
        public bool RightAnchorNotLifted_2 { get; set; }
        public bool ClampNotRelaxed_2 { get; set; }
        public bool LargeCarBrakeNotOpen_2 { get; set; }
        public bool LargeCarFrequencyConverterNotPowered_2 { get; set; }
        public bool LargeCarBrakeContactAuxiliaryFault_2 { get; set; }
        public bool LargeCarFrequencyConverterContactAuxiliaryFault_2 { get; set; }
        public bool RotaryFrequencyConverterNotPowered_2 { get; set; }
        public bool RotaryFrequencyConverterContactAuxiliaryFault_2 { get; set; }
        public bool RotaryBrakeContactAuxiliaryFault_2 { get; set; }
        public bool VariableAmplitudeOilPumpMotorNotRunning_2 { get; set; }
        public bool SuspensionBeltBrakeContactAuxiliaryFault_2 { get; set; }
        public bool SuspensionBeltLoadingContactAuxiliaryFault_2 { get; set; }
        public bool SuspensionBeltUnloadingContactAuxiliaryFault_2 { get; set; }
        public bool SuspensionBeltFirstLevelDeviation_2 { get; set; }
        public bool BucketWheelLubricationPumpContactAuxiliaryFault_2 { get; set; }
        public bool WindproofSystemCableLimit1_2 { get; set; }
        public bool RotaryFrequencyConverterFault_2 { get; set; }
        public bool RotaryFanOverload_2 { get; set; }
        public bool RotaryBrakeResistorOverheatSwitch_2 { get; set; }
        public bool DiversionBaffleMotorOverload_2 { get; set; }
        public bool TailCarFirstLevelDeviationSwitch_2 { get; set; }
        public bool TailCarSecondLevelDeviationSwitch_2 { get; set; }
        public bool TailCarEmergencyStopSwitch_2 { get; set; }
        public bool RotaryLeftTurnForbiddenLimit_2 { get; set; }
        public bool RotaryRightTurnForbiddenLimit_2 { get; set; }
        public bool BucketWheelMaterialUnloadingRunning_2 { get; set; }
        public bool VariableAmplitudeUpperElectromagneticValveOpen_2 { get; set; }
        public bool SuspensionBeltLoadingRunning_2 { get; set; }
        public bool SuspensionBeltUnloadingRunning_2 { get; set; }
        public bool SuspensionBeltBrakeOpen_2 { get; set; }
        public bool BucketWheelMotorRunning_2 { get; set; }
        public bool BucketWheelLubricationPumpRunning_2 { get; set; }
        public bool DiversionBaffleDownRunning_2 { get; set; }
        public bool DiversionBaffleUpRunning_2 { get; set; }
        public bool VibrationMotorRunning_2 { get; set; }
        public bool VariableAmplitudeBoostValveOpen_2 { get; set; }
        public bool BaffleDownLimit_2 { get; set; }
        public bool BaffleUpLimit_2 { get; set; }
        public bool RotaryOverTorque_2 { get; set; }
        public bool VariableAmplitudeOilPumpMotorContactFault_2 { get; set; }
        public bool BucketWheelMotorContactAuxiliaryFault_2 { get; set; }
        public bool TailCarOilPumpMotorContactAuxiliaryFault_2 { get; set; }
        public bool VibrationMotorFault_2 { get; set; }
        public bool ReelEmptySwitch_2 { get; set; }
        public bool WindproofSystemCableNotOpen_2 { get; set; }
        public bool LargeCarLimitAction_2 { get; set; }// 200

        // 201
        public bool RotaryLimitAction_2 { get; set; }
        public bool VariableAmplitudeLimitAction_2 { get; set; }
        public bool ForbiddenZoneLimitAction_2 { get; set; }
        public bool RotaryCrashSwitchAction_2 { get; set; }
        public bool LargeCarCentralizedLubricationLowOilLevelAlarm_2 { get; set; }
        public bool LargeCarCentralizedLubricationOilBlockageAlarm_2 { get; set; }
        public bool RotaryCentralizedLubricationLowOilLevelAlarm_2 { get; set; }
        public bool RotaryCentralizedLubricationOilBlockageAlarm_2 { get; set; }
        public bool StrongWindPreAlarm_2 { get; set; }
        public bool BucketWheelCentralizedLubricationLowOilLevelAlarm_2 { get; set; }
        public bool BucketWheelCentralizedLubricationOilBlockageAlarm_2 { get; set; }
        public bool ManualGuideSlotLiftButton_2 { get; set; }
        public bool ManualBucketWheelSlotStopButton_2 { get; set; }
        public bool ManualBucketWheelSlotDownButton_2 { get; set; }
        public bool CentralBaffleManualLiftButton_2 { get; set; }
        public bool CentralBaffleManualStopButton_2 { get; set; }
        public bool CentralBaffleManualDownButton_2 { get; set; }
        public bool VariableAmplitudeOilHeaterManualStartupButton_2 { get; set; }
        public bool VariableAmplitudeOilHeaterManualStopButton_2 { get; set; }
        public bool VariableAmplitudeFanManualStartupButton_2 { get; set; }
        public bool VariableAmplitudeFanManualStopButton_2 { get; set; }
        public bool ElectricRoomEmergencyStopButtonAction_2 { get; set; }
        public bool CabinEmergencyStopButtonAction_2 { get; set; }
        public bool EmergencyStopRelayNot_2 { get; set; }
        public bool TransformerOverheatAlarm_2 { get; set; }
        public bool ElectricRoomPLCModulePowerFault_2 { get; set; }
        public bool CabinPLCModulePowerFault_2 { get; set; }
        public bool ElectricRoomFireAlarm_2 { get; set; }
        public bool CabinFireAlarm_2 { get; set; }
        public bool SuspensionBeltEmergencyStop_2 { get; set; }
        public bool TailCarBeltEmergencyStopSwitch_2 { get; set; }
        public bool LargeCarMainCircuitBreakerFault_2 { get; set; }
        public bool LargeCarMotorCircuitBreakerFault_2 { get; set; }
        public bool LargeCarBrakeCircuitBreakerFault_2 { get; set; }
        public bool Spare1_2 { get; set; }
        public bool CarFrequencyConverterFault_2 { get; set; }
        public bool LargeCarBrakeResistorOverheatJump_2 { get; set; }
        public bool CableReelMainCircuitBreakerFault_2 { get; set; }
        public bool CableReelMotorOverloading_2 { get; set; }
        public bool PowerReelCableOverLooseAlarm_2 { get; set; }
        public bool PowerReelCableOverTightAlarm_2 { get; set; }
        public bool PowerReelFullDiskAlarm_2 { get; set; }
        public bool PowerReelEmptyDiskAlarm_2 { get; set; }
        public bool LargeCarOperationHandleFault_2 { get; set; }
        public bool RotaryMainCircuitBreakerFault_2 { get; set; }
        public bool RotaryBrakeOverloadAlarm_2 { get; set; }
        public bool RotaryFanOverloadAlarm_2 { get; set; }
        public bool RotaryFrequencyConverterFaulting_2 { get; set; }
        public bool RotaryBrakeResistorOverheatSwitching_2 { get; set; }
        public bool RotaryOverTorqueSwitch_2 { get; set; }
        public bool ReversalHandleFault_2 { get; set; }
        public bool LinkedBucketWheelNotRunning_2 { get; set; }
        public bool VariableFrequencyMainCircuitBreakerFault_2 { get; set; }
        public bool VariableFrequencyMotorOverload_2 { get; set; }
        public bool VariableFrequencyPumpClogged_2 { get; set; }
        public bool VariableFrequencyPumpStationHighTemperatureAlarm_2 { get; set; }
        public bool VariableFrequencyOilTankLowLevelAlarm_2 { get; set; }
        public bool Spare2_2 { get; set; }
        public bool VariableFrequencyHandleFault_2 { get; set; }
        public bool SuspendedBeltCircuitBreakerFault_2 { get; set; }
        public bool SuspendedBeltMotorOverload_2 { get; set; }
        public bool SuspendedBeltSecondLevelDeviationSwitch_2 { get; set; }
        public bool SuspendedBeltEmergencyStop_2 { get; set; }
        public bool SuspendedBeltSlip_2 { get; set; }
        public bool SuspendedBeltLongitudinalTearSwitch_2 { get; set; }
        public bool CentralHopperCloggedDetectionSwitch_2 { get; set; }
        public bool StackingSwitchFault_2 { get; set; }
        public bool CentralControlRoomNoStackingCommand_2 { get; set; }
        public bool BucketWheelMotorMainCircuitBreakerFault_2 { get; set; }
        public bool BucketWheelMotorOverloading_2 { get; set; }
        public bool BucketWheelOverTorqueSwitching_2 { get; set; }
        public bool BucketWheelTemperatureUpperLimitAlarm_2 { get; set; }
        public bool ClampingDeviceMainCircuitBreakerFault_2 { get; set; }
        public bool ClampingDeviceMotorOverload_2 { get; set; }
        public bool LeftClampingDeviceTimeout_2 { get; set; }
        public bool RightClampingDeviceTimeout_2 { get; set; }
        public bool StrongWindAlarm_2 { get; set; }
        public bool DryFogSystemLowAirPressure_2 { get; set; }
        public bool DryFogSystemLowWaterPressure_2 { get; set; }
        public bool DryFogSystemFilterClogged_2 { get; set; }
        public bool DryFogSystemWaterTankLowLevel_2 { get; set; }
        public bool DiversionPlateCircuitBreakerFault_2 { get; set; }
        public bool DiversionPlateMotorOverload_2 { get; set; }
        public bool DiversionPlateTimeout_2 { get; set; }
        public bool CentralControlRoomNoStackingOrDiversionCommand_2 { get; set; }
        public bool BucketWheelFeederCircuitBreakerFault_2 { get; set; }
        public bool BucketWheelFeederMotorOverload_2 { get; set; }
        public bool BucketWheelFeederTimeout_2 { get; set; }
        public bool CentralControlRoomNoStackingUnloadingCommand_2 { get; set; }
        public bool TailCarBeltFirstLevelDeviation_2 { get; set; }
        public bool TailCarBeltSecondLevelDeviation_2 { get; set; }
        public bool TailCarBeltLongitudinalTear_2 { get; set; }
        public bool Spare3_2 { get; set; }//293
        public bool VibrationMotorCircuitBreakerFault_2 { get; set; }
        public bool VibrationMotorOverloading_2 { get; set; }
        public bool DriverRoomEmergencyStopButton_2 { get; set; }
        public bool ElectricalRoomEmergencyStopButton_2 { get; set; }
        public bool EmergencyStopRelay_2 { get; set; }
        public bool TwoMachineCollisionAlarm_2 { get; set; }
        public bool RollerFullDiskSwitch_2 { get; set; }
        public bool RollerMiddleSwitch_2 { get; set; }
        public bool BucketWheelMotorContactor_2 { get; set; }
        public bool VariableFrequencyOilBlockageSignal_2 { get; set; }
        public bool VariableFrequencyOverpressureStop_2 { get; set; }
        public bool VariableFrequencyPumpStationOverpressureAlarm_2 { get; set; }
        public bool PowerRollerRunning_2 { get; set; }
        public bool DriverRoomLevelingContactor_2 { get; set; }
        public bool DryFogSystemIsLowAirPressure_2 { get; set; }
        public bool DryFogSystemIsLowWaterPressure_2 { get; set; }
        public bool WaterTankLowLevelSwitch_2 { get; set; }
        public bool DriverRoomRiseValve_2 { get; set; }
        public bool DriverRoomDescentValve_2 { get; set; }
        public bool PowerCableRollerNotRunning_2 { get; set; }
        public bool TailCarDrivenRollerBearingTemperatureUpperLimitAlarm_2 { get; set; }
        public bool TailCarDrivenRollerBearingTemperatureLowerLimitAlarm_2 { get; set; }
        public bool AllowBucketWheelDiversion_2 { get; set; }
        public bool WindproofSystemCableLimit2_2 { get; set; }
        public bool WindproofSystemCableLimit3_2 { get; set; }
        public bool RollerOverTightLimit2_2 { get; set; }
        public bool RollerOverLooseLimit2_2 { get; set; }
        public bool DryFogSystemFilterIsClogged_2 { get; set; }
        public bool DryFogSystemAutoRun_2 { get; set; }
        public bool DryFogSystemManualRun_2 { get; set; }
        public bool DryFogSystemSprayStatus_2 { get; set; }
        public bool DryFogSystemHeatRun_2 { get; set; }
        public bool BucketWheelSlotMainCircuitBreaker_2 { get; set; }
        public bool BucketWheelSlotMotorOverload_2 { get; set; }
        public bool TailCarBeltLongitudinalTearing_2 { get; set; }
        public bool ReversalBrakeRelease_2 { get; set; }
        public bool BucketWheelSlotLiftLimit_2 { get; set; }
        public bool BucketWheelSlotLowerLimit_2 { get; set; }
        public bool DiversionPlateLimit_2 { get; set; }
        public bool SuspendedBeltBrakeRelease_2 { get; set; }
        public bool BrokenBeltCaptureAlarm_2 { get; set; }
        public bool BucketWheelCentralizedLubricationLowOilLevel_2 { get; set; }
        public bool BucketWheelCentralizedLubricationClogged_2 { get; set; }
        public bool DriverRoomRearBalanceLimit_2 { get; set; }
        public bool BucketWheelDiversionRunning_2 { get; set; }
        public bool DriverRoomLevelingPumpRunning_2 { get; set; }
        public bool BucketWheelSlotLift_2 { get; set; }
        public bool BucketWheelSlotLower_2 { get; set; }
        public bool RemoteEmergencyStop_2 { get; set; }
        public ushort DiversionPlateAngle_2 { get; set; }
        public bool DryFogDustSuppressionStackingRunning_2 { get; set; }
        public bool DryFogDustSuppressionReclaimingRunning_2 { get; set; }
        public bool DryFogDustSuppressionDiversionRunning_2 { get; set; }
        public bool DryFogDustSuppressionRemoteStartRunning_2 { get; set; }
        public bool DryFogDustSuppressionRemoteStopRunning_2 { get; set; }// 348
        public bool TailCarDrivenRollerBearingUpperLimitAlarm_2 { get; set; }
        public bool TailCarDrivenRollerBearingLowerLimitAlarm_2 { get; set; }
        public bool UnmannedEmergencyStop_2 { get; set; }
        public bool RemoteEmergencyStoping_2 { get; set; }
        public bool LargeVehicleMotor1OvertemperatureAlarm_2 { get; set; }
        public bool LargeVehicleMotor2OvertemperatureAlarm_2 { get; set; }
        public bool LargeVehicleMotor3OvertemperatureAlarm_2 { get; set; }
        public bool LargeVehicleMotor4OvertemperatureAlarm_2 { get; set; }
        public bool LargeVehicleMotor5OvertemperatureAlarm_2 { get; set; }
        public bool LargeVehicleMotor6OvertemperatureAlarm_2 { get; set; }
        public bool WalkingReducerBearingTemperatureUpperLimitAlarm_2 { get; set; }
        public bool WalkingReducerBearingTemperatureLowerLimitAlarm_2 { get; set; }
        public bool WalkingReducerOilTemperatureUpperLimitAlarm_2 { get; set; }
        public bool WalkingReducerOilTemperatureLowerLimitAlarm_2 { get; set; }
        public bool ReversalTemperatureUpperLimitAlarm_2 { get; set; }
        public bool ReversalTemperatureLowerLimitAlarm_2 { get; set; }
        public bool BrokenBeltCaptureAlarming_2 { get; set; }
        public bool SuspendedBeltTemperatureUpperLimitAlarm_2 { get; set; }
        public bool SuspendedBeltTemperatureLowerLimitAlarm_2 { get; set; }
        public bool SuspendedBeltRollerBearingTemperatureUpperLimitAlarm_2 { get; set; }
        public bool SuspendedBeltRollerBearingTemperatureLowerLimitAlarm_2 { get; set; }
        public bool BucketWheelTemperatureLowerLimitAlarm_2 { get; set; }
        public bool CableRollerContactorAuxiliaryContactFault_2 { get; set; }
        public bool DriverRoomBalancePumpMotorNotRunning_2 { get; set; }
        public bool DriverRoomBalancePumpMotorAuxiliaryContactFault_2 { get; set; }
        public bool Remote_2 { get; set; }
        public ushort TwoMachineDistance_2 { get; set; } //两机距离
        public ushort DriverRoomAngle_2 { get; set; } //司机室角度
        public bool DriverRoomRiseButton_2 { get; set; }
        public bool DriverRoomDescentButton_2 { get; set; }

    }
}
